language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: 1DQeSdYZchgOhzznbJBu4KiyZZifmHzfMhJcD818MAE+KHdU0c/dc0Pn9h6Lw89RiOX+X1FYWdOpAVZN4IEk5364Muvhjtsq0+XL+0dZ1fraRxdzAWTQHlSDR1MuTBEZhyftO2Qg/4gWtQridps9zJ82ZUXQzGeV9nGzb8Vd27Y=
  on:
    tags: true
    repo: noflo/noflo-xml
